name: Create Pull Request
on:
  workflow_call:

jobs:
  create_pr:
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'branch' }}
    steps:
      - run: |
          echo "::debug::Creating new PR:"
          echo "::debug::   - repository: $REPO_NAME"
          echo "::debug::   - branch:     $BRANCH_NAME"
          echo "::debug::   - assignee:   $BRANCH_OWNER"
          if echo $( gh pr create --repo $REPO_NAME --assignee $BRANCH_OWNER --head $BRANCH_NAME --draft --title "$BRANCH_NAME" --body "Auto PR" 2>&1 >/dev/null ) | grep -q "Draft pull requests are not supported" 
          then
            echo "::debug::Repository does not support draft pull requests"
            gh pr create --repo $REPO_NAME --assignee $BRANCH_OWNER --head $BRANCH_NAME --title "$BRANCH_NAME" --body "Auto PR"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
          BRANCH_OWNER: ${{ github.actor }}
          REPO_NAME: ${{ github.repository }}
